#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MobileTasks.Droid.Resource", IsApplication=true)]

namespace MobileTasks.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ai_cancel = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ai_discard = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ai_edit = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ai_new = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ai_save = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int background = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int IconCompleted = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int icondetail = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int IconFacebook = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int IconGoogle = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int IconIncomplete = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int IconMicrosoft = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int IconPastDue = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int IconTwitter = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int Logo = 2130837519;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060009
			public const int completed = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int date = 2131099656;
			
			// aapt resource value: 0x7f06000d
			public const int dateDue = 2131099661;
			
			// aapt resource value: 0x7f060007
			public const int dateLabel = 2131099655;
			
			// aapt resource value: 0x7f06000a
			public const int delete = 2131099658;
			
			// aapt resource value: 0x7f060006
			public const int description = 2131099654;
			
			// aapt resource value: 0x7f06000f
			public const int edit = 2131099663;
			
			// aapt resource value: 0x7f060002
			public const int facebook = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int google = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int logo = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int microsoft = 2131099651;
			
			// aapt resource value: 0x7f06000e
			public const int newTask = 2131099662;
			
			// aapt resource value: 0x7f06000b
			public const int save = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int state = 2131099660;
			
			// aapt resource value: 0x7f060005
			public const int taskLabel = 2131099653;
			
			// aapt resource value: 0x7f060001
			public const int twitter = 2131099649;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Login = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int TaskDetail = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int TaskView = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int MainMenu = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int TaskMenu = 2131034113;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f04000b
			public const int Completed = 2130968587;
			
			// aapt resource value: 0x7f04000a
			public const int DateDue = 2130968586;
			
			// aapt resource value: 0x7f040006
			public const int Delete = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int Edit = 2130968581;
			
			// aapt resource value: 0x7f040001
			public const int Facebook = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int Google = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int Microsoft = 2130968578;
			
			// aapt resource value: 0x7f04000e
			public const int NewTask = 2130968590;
			
			// aapt resource value: 0x7f040008
			public const int No = 2130968584;
			
			// aapt resource value: 0x7f04000d
			public const int Ok = 2130968589;
			
			// aapt resource value: 0x7f04000c
			public const int Save = 2130968588;
			
			// aapt resource value: 0x7f040009
			public const int Task = 2130968585;
			
			// aapt resource value: 0x7f040003
			public const int Twitter = 2130968579;
			
			// aapt resource value: 0x7f040007
			public const int Yes = 2130968583;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
